Repository cancervariants/variation-normalization, pull requests merged in 2024-07, with the labels that each got.

#558 cicd: update precommit
  .pre-commit-config.yaml
  pyproject.toml
Labels: priority:low

#556 cicd: update workflows/templates from template repo
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/feature-request.yaml
  .github/workflows/checks.yaml
  .github/workflows/release.yml
  .github/workflows/stale.yaml
Labels: priority:low

#559 feat: enable more precise logging configuration
  src/variation/__init__.py
  src/variation/log_config.py
  src/variation/main.py
  src/variation/validators/genomic_base.py
  tests/conftest.py
Labels: priority:low

#560 cicd: update precommit dependency in pipfile
  Pipfile
Labels: priority:low

#561 build!: update ga4gh.vrs, cool-seq-tool, + gene-normalizer
  Pipfile
  pyproject.toml
  src/variation/gnomad_vcf_to_protein_variation.py
  src/variation/main.py
  src/variation/query.py
  src/variation/schemas/gnomad_vcf_to_protein_schema.py
  src/variation/schemas/token_response_schema.py
  src/variation/to_copy_number_variation.py
  src/variation/utils.py
  src/variation/validate.py
  src/variation/validators/validator.py
  tests/conftest.py
Labels: priority:medium, build

#563 fix(cicd): add reference to stalebot
  .github/workflows/stale.yaml
Labels: bug, priority:low, ci/cd

#565 fix: __version__ imports
  src/variation/gnomad_vcf_to_protein_variation.py
  src/variation/normalize.py
  src/variation/schemas/copy_number_schema.py
  src/variation/schemas/hgvs_to_copy_number_schema.py
  src/variation/schemas/normalize_response_schema.py
  src/variation/schemas/service_schema.py
  src/variation/schemas/to_vrs_response_schema.py
  src/variation/to_copy_number_variation.py
  src/variation/to_vrs.py
Labels: bug, priority:high

#568 chore: remove unused files
  .coveragerc
  Dockerfile
  biomart.png
  cron.yaml
Labels: priority:low, chore

#567 style: ruff format
  src/variation/gnomad_vcf_to_protein_variation.py
  src/variation/normalize.py
  src/variation/schemas/copy_number_schema.py
  src/variation/schemas/hgvs_to_copy_number_schema.py
  src/variation/schemas/service_schema.py
  src/variation/to_copy_number_variation.py
  src/variation/to_vrs.py
Labels: cleanup, priority:high

#566 fix: TypeError for params that accept union of enums
  src/variation/hgvs_dup_del_mode.py
  src/variation/translators/translator.py
Labels: bug, priority:high

#564 chore: update ebextensions for downloading latest seqrepo instance
  .ebextensions/01_download_data.config
Labels: priority:high, chore

#569 cicd: allow missing credentials in aws creds detection
  .pre-commit-config.yaml
Labels: priority:low

#570 feat!: add `sequence` to `SequenceLocation`
  src/variation/gnomad_vcf_to_protein_variation.py
  src/variation/normalize.py
  src/variation/schemas/gnomad_vcf_to_protein_schema.py
  src/variation/to_copy_number_variation.py
  src/variation/to_vrs.py
  src/variation/utils.py
  tests/conftest.py
  tests/test_gnomad_vcf_to_protein.py
  tests/test_hgvs_dup_del_mode.py
  tests/test_normalize.py
  tests/to_copy_number_variation/test_hgvs_to_copy_number.py
Labels: enhancement, priority:medium

#571 fix: update ga4gh.vrs + add back response_model configs for FastAPI
  Pipfile
  pyproject.toml
  src/variation/main.py
  tests/test_normalize.py
Labels: bug, priority:medium, build

#572 docs: update vrs versioning
  README.md
Labels: documentation, priority:medium

#573 docs: update vrs versioning
  README.md
Labels: documentation, priority:low

#575 build: pin cool-seq-tool~=0.6.0
  Pipfile
  pyproject.toml
  src/variation/gnomad_vcf_to_protein_variation.py
  src/variation/schemas/service_schema.py
  src/variation/translators/ambiguous_translator_base.py
  src/variation/translators/genomic_del_dup_base.py
  src/variation/translators/genomic_delins.py
  src/variation/translators/genomic_insertion.py
  src/variation/translators/genomic_reference_agree.py
  src/variation/translators/genomic_substitution.py
Labels: priority:medium, build

#576 feat: return MANE gene(s) in normalize endpoint for genomic queries
  src/variation/hgvs_dup_del_mode.py
  src/variation/translators/genomic_del_dup_base.py
  src/variation/translators/genomic_delins.py
  src/variation/translators/genomic_insertion.py
  src/variation/translators/genomic_reference_agree.py
  src/variation/translators/genomic_substitution.py
  src/variation/translators/translator.py
  src/variation/vrs_representation.py
  tests/conftest.py
  tests/test_hgvs_dup_del_mode.py
  tests/test_normalize.py
Labels: enhancement, priority:medium
