Repository cancervariants/variation-normalization, pull requests merged in 2025-03, with the labels that each got.

#600 cicd: update ruff and precommit checks
  .github/workflows/checks.yaml
  .gitignore
  .pre-commit-config.yaml
  pyproject.toml
  src/variation/classifiers/__init__.py
  src/variation/main.py
  src/variation/tokenizers/__init__.py
  src/variation/tokenizers/protein_deletion.py
  src/variation/tokenizers/protein_delins.py
  src/variation/translators/__init__.py
  src/variation/utils.py
  src/variation/validators/__init__.py
  tests/test_gnomad_vcf_to_protein.py
  tests/test_hgvs_dup_del_mode.py
  tests/test_normalize.py
  tests/test_translator.py
  tests/test_validator.py
  tests/to_copy_number_variation/test_hgvs_to_copy_number.py
Labels: priority:low

#604 chore: update seqrepo version to 2024-12-20
  .ebextensions/01_download_data.config
  README.md
Labels: priority:low, chore

#605 docs: update uta version to 20241220
  README.md
Labels: documentation, priority:low

#603 chore: update developer installation for uta
  README.md
  docker-compose.yaml
  uta-setup.sql
Labels: documentation, priority:low, chore

#606 build!: update cool-seq-tool version
  Pipfile
  pyproject.toml
Labels: priority:medium, build
