Repository cancervariants/variation-normalization, pull requests merged in 2025-07, with the labels that each got.

#613 feat: add docker install instructions
  .dockerignore
  Dockerfile
  README.md
  compose-dev.yaml
  compose.yaml
  docker-compose.yaml
Labels: enhancement, priority:low

#614 style: update ruff and precommit
  .pre-commit-config.yaml
  pyproject.toml
  src/variation/main.py
  src/variation/normalize.py
  src/variation/schemas/copy_number_schema.py
  src/variation/vrs_representation.py
  tests/to_copy_number_variation/test_amplification_to_cx_var.py
Labels: priority:low

#622 chore: add pipfile + uv lock to gitignore
  .gitignore
Labels: priority:low, chore

#626 feat: add input assembly parameter for /gnomad_vcf_to_protein
  src/variation/gnomad_vcf_to_protein_variation.py
  src/variation/main.py
  tests/test_gnomad_vcf_to_protein.py
Labels: enhancement, priority:medium
